const Sector = [
  { label: 'Manufacturing', value: 'Manufacturing' },
  { label: 'Construction materials', value: 'Construction materials' },
  { label: 'Electronics and Optics', value: 'Electronics and Optics' },
  { label: 'Food and Beverage', value: 'Food and Beverage' },
  {
    label: 'Bakery & confectionery products',
    value: 'Bakery & confectionery products',
  },
  { label: 'Beverages', value: 'Beverages' },
  { label: 'Fish & fish products', value: 'Fish & fish products' },
  { label: 'Meat & meat products', value: 'Meat & meat products' },
  { label: 'Milk & dairy products', value: 'Milk & dairy products' },
  { label: 'Other', value: 'Other' },
  { label: 'Sweets & snack food', value: 'Sweets & snack food' },
  { label: 'Furniture', value: 'Furniture' },
  { label: 'Bathroom/sauna', value: 'Bathroom/sauna' },
  { label: 'Bedroom', value: 'Bedroom' },
  { label: 'Children’s room', value: 'Children’s room' },
  { label: 'Kitchen', value: 'Kitchen' },
  { label: 'Living room', value: 'Living room' },
  { label: 'Office', value: 'Office' },
  { label: 'Other (Furniture)', value: 'Other (Furniture)' },
  { label: 'Outdoor', value: 'Outdoor' },
  { label: 'Project furniture', value: 'Project furniture' },
  { label: 'Machinery', value: 'Machinery' },
  { label: 'Machinery components', value: 'Machinery components' },
  { label: 'Machinery equipment/tools', value: 'Machinery equipment/tools' },
  { label: 'Manufacture of machinery', value: 'Manufacture of machinery' },
  { label: 'Maritime', value: 'Maritime' },
  {
    label: 'Aluminium and steel workboats',
    value: 'Aluminium and steel workboats',
  },
  { label: 'Boat/Yacht building', value: 'Boat/Yacht building' },
  { label: 'Ship repair and conversion', value: 'Ship repair and conversion' },
  { label: 'Metal structures', value: 'Metal structures' },
  { label: 'Other', value: 'Other' },
  {
    label: 'Repair and maintenance service',
    value: 'Repair and maintenance service',
  },
  { label: 'Metalworking', value: 'Metalworking' },
  {
    label: 'Construction of metal structures',
    value: 'Construction of metal structures',
  },
  { label: 'Houses and buildings', value: 'Houses and buildings' },
  { label: 'Metal products', value: 'Metal products' },
  { label: 'Metal works', value: 'Metal works' },
  { label: 'CNC-machining', value: 'CNC-machining' },
  { label: 'Forgings, Fasteners', value: 'Forgings, Fasteners' },
  { label: 'Gas, Plasma, Laser cutting', value: 'Gas, Plasma, Laser cutting' },
  { label: 'MIG, TIG, Aluminum welding', value: 'MIG, TIG, Aluminum welding' },
  { label: 'Plastic and Rubber', value: 'Plastic and Rubber' },
  { label: 'Packaging', value: 'Packaging' },
  { label: 'Plastic goods', value: 'Plastic goods' },
  {
    label: 'Plastic processing technology',
    value: 'Plastic processing technology',
  },
  { label: 'Blowing', value: 'Blowing' },
  { label: 'Moulding', value: 'Moulding' },
  {
    label: 'Plastics welding and processing',
    value: 'Plastics welding and processing',
  },
  { label: 'Plastic profiles', value: 'Plastic profiles' },
  { label: 'Printing', value: 'Printing' },
  { label: 'Advertising', value: 'Advertising' },
  { label: 'Book/Periodicals printing', value: 'Book/Periodicals printing' },
  {
    label: 'Labelling and packaging printing',
    value: 'Labelling and packaging printing',
  },
  { label: 'Textile and Clothing', value: 'Textile and Clothing' },
  { label: 'Clothing', value: 'Clothing' },
  { label: 'Textile', value: 'Textile' },
  { label: 'Wood', value: 'Wood' },
  { label: 'Other (Wood)', value: 'Other (Wood)' },
  { label: 'Wooden building materials', value: 'Wooden building materials' },
  { label: 'Wooden houses', value: 'Wooden houses' },
  { label: 'Other', value: 'Other' },
  { label: 'Creative industries', value: 'Creative industries' },
  { label: 'Energy technology', value: 'Energy technology' },
  { label: 'Environment', value: 'Environment' },
  { label: 'Service', value: 'Service' },
  { label: 'Business Service', value: 'Business Service' },
  { label: 'Engineering', value: 'Engineering' },
  {
    label: 'Information Technology and Telecommunications',
    value: 'Information Technology and Telecommunications',
  },
  {
    label: 'Data processing, Web portals, E-marketing',
    value: 'Data processing, Web portals, E-marketing',
  },
  { label: 'Programming, Consultancy', value: 'Programming, Consultancy' },
  { label: 'Software, Hardware', value: 'Software, Hardware' },
  { label: 'Telecommunications', value: 'Telecommunications' },
  { label: 'Tourism', value: 'Tourism' },
  { label: 'Translation service', value: 'Translation service' },
  { label: 'Transport and Logistics', value: 'Transport and Logistics' },
  { label: 'Air', value: 'Air' },
  { label: 'Rail', value: 'Rail' },
  { label: 'Road', value: 'Road' },
  { label: 'Water', value: 'Water' },
];

export default Sector;
